### PR TITLE
Save autoshare meta from post form before publishing tweet

### LINKED ISSUE #80: Tweet shared when unchecked
When autoshare_for_twitter_enabled_default filter enabled:

**Steps to reproduce:**
- New Post
- Leave 'Tweet this Post' checked
- Save Draft
- Uncheck 'Tweet this Post'
- Save Draft/Publish
- Tweets out Post

### PR DESCRIPTION
**Pull request by johnwatkins0**
### Description of the Change

This resolves a bug brought up by @rickalee  in #80. Autoshare form data is saved in `save_post` while the tweet action runs on `transition_post_status`. `transition_post_status` runs earlier than `save_post`, so the bug happened in the case where:

1) The post is switching from from a non-publish status to publish
2) AND the autoshare status is switching from enabled to disabled.

In this case, the enabled status has not been saved before the tweet function runs, so the post is tweeted.

This update causes the form data to be processed before trying to tweet.

### Alternate Designs

I'm wanting to refactor large parts of this plugin, but I'm holding for now and will aim to submit issues outlining the specific technical debt I'm seeing.

### Benefits

Tweets won't be inadvertently published during the specific scenario outlined above.

### Verification Process

1. Create a new post
2. Leave 'Tweet this Post' checked
3. Save Draft
4. Uncheck 'Tweet this Post'
5. Save Draft/Publish
6. Post should **not** be tweeted

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

Resolves #80 

### Changelog Entry

Fix a bug that caused posts to be inadvertently tweeted when switching from draft to publish

### CODE REVIEW

**Comment by rickalee** [comment]
Confirmed all looks good on our side. Packaging up for client bugfix and will follow up if they catch anything.

**Comment by rickalee** [comment]
No reported issues after pushing to client site as hotfix and confirmed Twitter timeline looks good. Thanks @johnwatkins0 . I think we can safely add to next release.

**Comment by jeffpaul** [comment]
@johnwatkins0 are there any tests that we can add to cover this to avoid a regression back to this behavior later?

**Comment by johnwatkins0** [comment]
@jeffpaul Yes, we could definitely increase test coverage. I'll look into adding a unit test for this particular PR later. I'd also like to try #19 to see how well WPAcceptance can cover this sort of thing, but that should probably be a separate task because it will involve setting up acceptance tests and probably adding more than just this one.

**Comment by jeffpaul** [comment]
@rickalee @johnwatkins0 did either of you want/need to ship a v1.0.2 for this or hold and include in a larger v1.1.0 later?

File: includes/admin/post-meta.php [hunk 1]
```diff
@@ -46,30 +46,46 @@
...
-function save_tweet_meta( $post_id ) {
-	if ( ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) || ! current_user_can( 'edit_post', $post_id ) ) {
+function save_tweet_meta( $post_id, $post = null, $update = true ) {
+	if ( ! $update || ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) || ! current_user_can( 'edit_post', $post_id ) ) {
 		return;
 	}
 
-	$form_data = sanitize_autoshare_for_twitter_meta_data(
-		// Using FILTER_DEFAULT here as data is being passed to sanitize function.
-		filter_input( INPUT_POST, META_PREFIX, FILTER_DEFAULT, FILTER_REQUIRE_ARRAY )
```
Comment (johnwatkins0) [inline includes/admin/post-meta.php]: Broke this out into a function (see below) for easier testing.

**Comment by johnwatkins0** [comment]
I added some tests and also did some cleanup around meta saving. Sorry about the growing diff, @dinhtungdu . 

I'm aiming to use my extra time over the next few days to set up WP Acceptance ahead of a 1.1.0 release, but I'll work on that in a separate PR.

**Review by dinhtungdu — APPROVED** [review]
Worked great in my tests! 🎉
